apiVersion: apps/v1
kind: Deployment
metadata:
  name: planes-api-deployment
  labels:
    app: planes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planes-api
  template:
    metadata:
      labels:
        app: planes-api
    spec:
      containers:
        - name: planes-api
          image: ewenbouquet/planes-api:0.1.0-SNAPSHOT
          ports:
          - containerPort: 8080
          env:
          - name: API_HOST
            valueFrom:
              configMapKeyRef:
                name: planes-config
                key: planes-api-host
          - name: API_PORT
            valueFrom:
              configMapKeyRef:
                name: planes-config
                key: planes-api-port
          - name: HEALTH_CHECK_HOST
            valueFrom:
              configMapKeyRef:
                name: planes-config
                key: planes-api-health-check-host
          - name: HEALTH_CHECK_PORT
            valueFrom:
              configMapKeyRef:
                name: planes-config
                key: planes-api-health-check-port
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: planes-config
                key: postgres-service-name
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: planes-config
                key: postgres-port
          - name: DB_KEYSPACE
            valueFrom:
              configMapKeyRef:
                name: planes-config
                key: planes-api-postgres-db
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: planes-config
                key: postgres-user
          - name: DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: planes-config
                key: postgres-password
          livenessProbe:
            httpGet:
              path: /health-check
              port: 8081
            initialDelaySeconds: 60s
            periodSeconds: 60s
            timeoutSeconds: 30s
            failureThreshold: 3
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.28
          env:
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: planes-config
                  key: postgres-service-name
            - name: RETRY_DELAY
              value: '15'
          command: ['sh', '-c', "until nslookup $SERVICE_NAME.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for $SERVICE_NAME; sleep $RETRY_DELAY; done; echo ; echo Service available: end of task!"]
        - name: flyway
          image: ewenbouquet/flyway:latest
          args: [
            "-url=jdbc:postgresql://postgres-service:5432/db_ewen?allowPublicKeyRetrieval=true",
            "-schemas=db_ewen",
            "-user=admin",
            "-password=root",
            "-connectRetries=60",
            "-validateMigrationNaming=true",
            "migrate"
          ]
---
apiVersion: v1
kind: Service
metadata:
  name: planes-api-service
spec:
  type: NodePort
  selector:
    app: planes-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
