apiVersion: apps/v1
kind: Deployment
metadata:
  name: planes-broker-producer-deployment
  labels:
    app: planes-broker-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planes-broker-producer
  template:
    metadata:
      labels:
        app: planes-broker-producer
    spec:
      containers:
        - name: planes-broker-producer
          image: ewenbouquet/planes-broker-producer:0.1.0-SNAPSHOT
          ports:
            - containerPort: 8080
          env:
            - name: BROKER_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: planes-config
                  key: broker-url
            - name: BROKER_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: planes-config
                  key: planes-broker-producer-topic
            - name: BROKER_SCHEDULER_INITIAL_DELAY
              valueFrom:
                configMapKeyRef:
                  name: planes-config
                  key: planes-broker-producer-initial-delay
            - name: BROKER_SCHEDULER_REFRESH_DELAY
              valueFrom:
                configMapKeyRef:
                  name: planes-config
                  key: planes-broker-producer-refresh-delay
      initContainers:
        - name: wait-for-broker
          image: busybox:1.28
          env:
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: planes-config
                  key: broker-service-name
            - name: RETRY_DELAY
              value: '15'
          command: ['sh', '-c', "until nslookup $SERVICE_NAME.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for $SERVICE_NAME; sleep $RETRY_DELAY; done"]
