apiVersion: apps/v1
kind: Deployment
metadata:
  name: planes-api-deployment
  labels:
    app: planes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planes-api
  template:
    metadata:
      labels:
        app: planes-api
    spec:
      containers:
        - name: planes-api
          image: ewenbouquet/planes-api:0.1.0-SNAPSHOT
          ports:
          - containerPort: 8080
          env:
          - name: API_HOST
            valueFrom:
              configMapKeyRef:
                name: planes-config
                key: planes-api-host
          - name: API_PORT
            valueFrom:
              configMapKeyRef:
                name: planes-config
                key: planes-api-port
          - name: DATABASE_CONTACT_POINT
            valueFrom:
              configMapKeyRef:
                name: planes-config
                key: cassandra-url
          - name: DATABASE_KEYSPACE
            valueFrom:
              configMapKeyRef:
                name: planes-config
                key: planes-api-cassandra-keyspace
          - name: DATABASE_DATACENTER
            valueFrom:
              configMapKeyRef:
                name: planes-config
                key: cassandra-datacenter
      initContainers:
        - name: wait-for-cassandra
          image: busybox:1.28
          env:
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: planes-config
                  key: cassandra-service-name
            - name: RETRY_DELAY
              value: '15'
          command: ['sh', '-c', "until nslookup $SERVICE_NAME.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for $SERVICE_NAME; sleep $RETRY_DELAY; done; echo ; echo Service available: end of task!"]
        - name: wait-for-broker
          image: busybox:1.28
          env:
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: planes-config
                  key: broker-service-name
            - name: RETRY_DELAY
              value: '15'
          command: ['sh', '-c', "until nslookup $SERVICE_NAME.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for $SERVICE_NAME; sleep $RETRY_DELAY; done; echo ; echo Service available: end of task!"]
---
apiVersion: v1
kind: Service
metadata:
  name: planes-api-service
spec:
  type: NodePort
  selector:
    app: planes-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
