apiVersion: apps/v1
kind: Deployment
metadata:
  name: planes-broker-consumer-deployment
  labels:
    app: planes-broker-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planes-broker-consumer
  template:
    metadata:
      labels:
        app: planes-broker-consumer
    spec:
      containers:
        - name: planes-broker-consumer
          image: ewenbouquet/planes-broker-consumer:0.1.0-SNAPSHOT
          ports:
            - containerPort: 8080
          env:
            - name: BROKER_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: planes-config
                  key: broker-url
            - name: BROKER_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: planes-config
                  key: planes-broker-consumer-planes-topic
            - name: DATABASE_CONTACT_POINT
              valueFrom:
                configMapKeyRef:
                  name: planes-config
                  key: cassandra-url
            - name: DATABASE_KEYSPACE
              valueFrom:
                configMapKeyRef:
                  name: planes-config
                  key: planes-broker-consumer-cassandra-keyspace
            - name: DATABASE_DATACENTER
              valueFrom:
                configMapKeyRef:
                  name: planes-config
                  key: cassandra-datacenter
      initContainers:
        - name: wait-for-cassandra
          image: busybox:1.28
          env:
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: planes-config
                  key: cassandra-service-name
            - name: RETRY_DELAY
              value: '15'
          command: ['sh', '-c', "until nslookup $SERVICE_NAME.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for $SERVICE_NAME; sleep $RETRY_DELAY; done; echo ; echo Service available: end of task!"]
        - name: wait-for-broker
          image: busybox:1.28
          env:
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: planes-config
                  key: broker-service-name
            - name: RETRY_DELAY
              value: '15'
          command: ['sh', '-c', "until nslookup $SERVICE_NAME.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for $SERVICE_NAME; sleep $RETRY_DELAY; done; echo ; echo Service available: end of task!"]
