apiVersion: v1
kind: ConfigMap
metadata:
  name: planes-config
data:

  ################################################################################################
  #> Environment                                                                                 #
  ################################################################################################

  # Cassandra
  cassandra-service-name: cassandra-service
  cassandra-url: cassandra-service:9042
  cassandra-datacenter: datacenter1

  # Zookeeper
  zookeeper-service-name: zookeeper-service
  zookeeper-url: zookeeper-service:2181
  zookeeper-tick-time: '2000'

  # Broker
  broker-service-name: broker-service
  broker-url: broker-service:9093
  broker-broker-id: '1'
  broker-listener-security-protocol-map: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  broker-advertised-listeners: PLAINTEXT://:9092,PLAINTEXT_HOST://broker-service:9093
  broker-offsets-topic-replication-factor: '1'
  broker-transaction-state-log-min-isr: '1'
  broker-transaction-state-log-replication-factor: '1'


  ################################################################################################
  #> Services                                                                                    #
  ################################################################################################

  # Planes api
  planes-api-service-name: planes-api-service
  planes-api-cassandra-keyspace: 'production'
  planes-api-host: 0.0.0.0
  planes-api-port: '8080'

  # Planes broker producer
  planes-broker-producer-service-name: planes-broker-producer-service
  planes-broker-producer-topic: 'ewenbouquet_planes'
  planes-broker-producer-initial-delay: 5 seconds
  planes-broker-producer-refresh-delay: 1 minute

  # Planes broker consumer
  planes-broker-consumer-service-name: planes-broker-consumer-service-service
  planes-broker-consumer-planes-topic: 'ewenbouquet_planes'
  planes-broker-consumer-cassandra-keyspace: 'production'
